services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.entity_manager'

    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface: '@lexik_jwt_authentication.jwt_manager'

    App\Service\PusherService:
        arguments:
            $appId:     '%env(default::PUSHER_APP_ID)%'
            $appKey:    '%env(default::PUSHER_APP_KEY)%'
            $appSecret: '%env(default::PUSHER_APP_SECRET)%'
            $cluster:   '%env(default::PUSHER_APP_CLUSTER)%'
