parameters:
    pusher_cluster_default: 'eu'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Doctrine\ORM\EntityManagerInterface:
        public: true

    Lexik\Bundle\JWTAuthenticationBundle\Services\JWTTokenManagerInterface:
        public: true

    App\Service\PusherService:
        arguments:
            $appId:     '%env(default::PUSHER_APP_ID)%'
            $appKey:    '%env(default::PUSHER_APP_KEY)%'
            $appSecret: '%env(default::PUSHER_APP_SECRET)%'
            $cluster:   '%env(default:pusher_cluster_default:PUSHER_APP_CLUSTER)%'
