lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    clock_skew: 0
    user_id_claim: email  
    
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: false
        query_parameter:
            enabled: false

    # Configuration pour le set de cookies (optionnel)
    set_cookies:
        jwt:
            lifetime: 3600
            samesite: lax
            path: /
            secure: true  # true en production (HTTPS)
            httpOnly: true