nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['https://guardtrack-pro.vercel.app']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'ngrok-skip-browser-warning']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['https://guardtrack-pro.vercel.app']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'ngrok-skip-browser-warning']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 36000